#!/bin/bash

echo -e "Hello! This is setup script for insoftretail audio client. Press any key to continue... \c "
read any_key

echo "Installing VLC media player... \n"
sudo apt-get install vlc

echo "Install RVM libs...\n"

sudo apt-get install build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion

echo "Download and install rvm... \n"
curl -L get.rvm.io | bash -s stable

echo "Modifying .bashrc file for autoloading rvm... \n"
echo ". ~/.rvm/scripts/'rvm'" >> ~/.bashrc

echo "Load rvm in bash... \n"
. ~/.rvm/scripts/'rvm'

echo "Installing ruby... \n"
rvm install 1.9.3-head

echo "use ruby 1.9.3... \n"
rvm use 1.9.3-head --default

echo "Install project files: \n"

bundle install
whenever --update-crontab
