#!/usr/bin/env ruby


require File.dirname(File.absolute_path(__FILE__)) + "/../config/application"

puts `#{AudioClient::Application.base_path}/script/updater`

AudioClient::Application.new do
  begin
    AudioClient::Utils::ProcessManager.kill_all_processes
  
    AudioClient::FileUpdater.start
    AudioClient::MusicPlayer.stop
    AudioClient::PlaylistBuilder.build
    AudioClient::MusicPlayer.start
  rescue Exception => e
    puts e.class
    puts e.message
    puts e.backtrace
    sleep(20) 
  end
end