#!/usr/bin/env ruby


require File.dirname(File.absolute_path(__FILE__)) + "/../config/application"

puts `#{AudioClient::Application.base_path}/script/updater`

AudioClient::Application.new do
  AudioClient::Utils::ProcessManager.kill_all_processes
  
  AudioClient::FileUpdater.start
  AudioClient::PlaylistBuilder.build
  AudioClient::MusicPlayer.stop
  AudioClient::MusicPlayer.start
end