#!/usr/bin/env ruby


require File.dirname(File.absolute_path(__FILE__)) + "/../config/application"

puts `#{AudioClient::Application.base_path}/script/updater`

AudioClient::Application.new(:dev) do
  AudioClient::FileUpdater.start
  AudioClient::PlaylistBuilder.build
  AudioClient::MusicPlayer.start
end